<?php

declare(strict_types=1);

namespace Akrista\Sequel\App;

use Akrista\Sequel\Interfaces\GenerationInterface;
use Akrista\Sequel\Traits\classResolver;
use Carbon\Carbon;
use Exception;
use Illuminate\Support\Facades\Artisan;

final class ModelAction implements GenerationInterface
{
    use classResolver;

    /**
     * ControllerAction constructor.
     */
    public function __construct(private string $database, private string $table) {}

    /**
     * Generate
     */
    public function generate(): string
    {
        Artisan::call('make:model', [
            'name' => $this->generateModelName($this->table),
        ]);

        $this->setActualTable(
            $this->table,
            $this->configNamespaceResolver('model')->suffix === ''
        );

        $this->dumpAutoload();

        return (string) $this->getQualifiedName();
    }

    /**
     * If user has set a suffix for their models this method will add a protected $table attribute to their model.
     * This will also a timestamp and Sequel signature at the top of every model generated by Sequel.
     */
    public function setActualTable(string $table, bool $onlyMark = false): int|false
    {
        // Get path for Model
        $path = base_path('app/' . $this->generateModelName($table) . '.php');
        $path = preg_replace("~[\\\/]~", DIRECTORY_SEPARATOR, $path);

        $content = file_get_contents($path);

        if ($onlyMark) {
            // Replacement attribute, kindly do not touch! :)
            $comment =
                '// Better model organisation and an automatic $table attribute setter, this saved you at least 2 seconds! - Sequel';
            $replacement =
                $comment . "\n    protected \$table = '" . $table . "';";

            // Replace the double slashes (//) in the newly created model with an attribute for the actual table name.
            $content = preg_replace('@//@', $replacement, $content);
        }

        // Stamp
        $stamp = "<?php\n\n// Generated by Sequel @" . Carbon::now();
        $content = preg_replace("@<\?php@", $stamp, $content);

        return file_put_contents($path, $content);
    }

    /**
     * STUB
     */
    public function setActualConnection(): void
    {
        // STUB
    }

    /**
     * Get fully qualified class name
     */
    public function getQualifiedName(): string|false
    {
        try {
            return $this->generateModelName($this->table);
        } catch (Exception) {
            return false;
        }
    }

    /**
     * Get class name
     */
    public function getClassname(): false|string
    {
        $class = $this->getQualifiedName();

        if (!$class) {
            return false;
        }

        $arr = explode('\\', $class);
        $count = count($arr);

        return $arr[$count - 1];
    }

    /**
     * Get class namespace
     */
    public function getNamespace(): false|string
    {
        if (!$this->getQualifiedName()) {
            return false;
        }

        $arr = explode('\\', (string) $this->getQualifiedName());
        $count = count($arr);
        $namespace = '';

        for ($i = 0; $i < $count; $i++) {
            if ($i === $count - 1) {
                break;
            }

            $namespace .= $arr[$i] . '\\';
        }

        return $namespace;
    }
}
